language: rust
rust:
  - nightly
matrix:
  allow_failure:
    - rust: nightly
sudo: false

addons:
  apt:
    packages:
    - gcc-arm-none-eabi
    - foobarbaz

before_install:
  - mkdir build
  - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
  - tar -xf gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2

script: make build/main.elf
