language: rust
rust:
  - nightly
matrix:
  allow_failure:
    - rust: nightly
sudo: false

addons:
  apt:
    packages:
    - gcc-arm-none-eabi

before_install:
  - mkdir build

script: make build/main.elf
