language: rust
rust:
  - nightly
matrix:
  allow_failure:
    - rust: nightly
sudo: false

before_install:
  - mkdir build
  - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
  - tar -xvf gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2

script: make TOOLCHAIN=$PWD/gcc-arm-none-eabi-4_9-2014q4/bin/arm-none-eabi- build/main.elf
